modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/suppergerrie2/PanoramaMod/issues"
license="GNU General Public License v3.0"

[[mods]]
modId="spanorama"
version="${file.jarVersion}"
updateJSONURL="https://raw.githubusercontent.com/suppergerrie2/PanoramaMod/master/update.json"
displayName="Panorama"
displayURL="https://www.curseforge.com/minecraft/mc-mods/panorama-creator"
credits="liachmodded for making runorama which helped a lot and Cadiboo for his example on keybindings"
authors="suppergerrie2"
description='''
Adds the ability to make panoramas in minecraft, these can then be put in resourcepacks to display on the main menu.
'''